### PR TITLE
Created navbar and footer for desktop. Starting layout for members page

### PR DESCRIPTION
**Pull request by henrybliu**

### CODE REVIEW

**Comment by henrybliu** [comment]
added footer

**Comment by henrybliu** [comment]
created members banner and created card component

**Comment by andrewt319** [comment]
idk how serious we wanna go about things but i feel like might b better practice to move all the styling into its own directory so its less cluttered and remove unused imports, console.logs, etc so the codebase and code r cleaner. otherwise i think it looks good doe

**Comment by henrybliu** [comment]
> 

great idea!

**Review by amoghm01 — APPROVED** [review]

**Pull request merged**
